### Import Statements 

In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf

### Versions

In [5]:
print 'tensorflow version ',tf.__version__
print 'pandas version ',pd.__version__
print 'numpy version ', np.__version__

tensorflow version  1.12.0
pandas version  0.23.4
numpy version  1.15.4


# Basics
Converts list to numpy array object. Numpy arrays have many attractive features such as the ability to select subsets using masks and the datatype can be specified.

In [6]:
np.array(object=[[1, 9, 9, 1], [2, 0, 1, 6]], dtype=np.float32)


array([[1., 9., 9., 1.],
       [2., 0., 1., 6.]], dtype=float32)

In [7]:
np.zeros(shape=(2, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### arange
Create an array of evenly spaced values.

In [9]:
np.arange(start=1.5, stop=8.5, step=0.7, dtype=float)

array([1.5, 2.2, 2.9, 3.6, 4.3, 5. , 5.7, 6.4, 7.1, 7.8])

### sqrt
Takes the square root of input.

In [10]:
np.sqrt([16, 9, 4])

array([4., 3., 2.])

### ones
Create numpy array of ones.

In [11]:
np.ones(shape=(2, 3, 1), dtype=np.unicode)

array([[[u'1'],
        [u'1'],
        [u'1']],

       [[u'1'],
        [u'1'],
        [u'1']]], dtype='<U1')

### sum
Get sum of values along rows or columns.

In [13]:
vals = np.arange(0, 12, 1).reshape((3, 4))
print(vals)
print('')
print('sum entire array =', np.sum(vals))
print('sum along columns =', np.sum(vals, axis=0))
print('sum along rows =', np.sum(vals, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

('sum entire array =', 66)
('sum along columns =', array([12, 15, 18, 21]))
('sum along rows =', array([ 6, 22, 38]))


### Mean
Along different axis

In [15]:

vals = np.array([1, 2, 3, 4]*3).reshape((3, 4))
print(vals)
print('')
print('mean entire array =', np.mean(vals))
print('mean along columns =', np.mean(vals, axis=0))
print('mean along rows =', np.mean(vals, axis=1))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]

('mean entire array =', 2.5)
('mean along columns =', array([1., 2., 3., 4.]))
('mean along rows =', array([2.5, 2.5, 2.5]))


### linspace
Create an array of evenly spaced values of defined length.

In [18]:
np.linspace(0, 19.3, 6)

array([ 0.  ,  3.86,  7.72, 11.58, 15.44, 19.3 ])

### asarray
Convert to numpy array. If input is already a ndarray then it will not be copied. The same result can be achieved with array by setting copy=False.

In [19]:
vals = np.array([9, 2, 3, 5])
print(type(vals))
print(vals)
a = np.asarray(vals)
a += 1
print(vals) # vals changes because it was not copied when assigning 'a'

<type 'numpy.ndarray'>
[9 2 3 5]
[10  3  4  6]


### keepdims

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left in the result as
    dimensions with size one. With this option, the result will broadcast
    correctly against the input array.
    
You will notice that if you don't specify an axis (1st two examples), the numerical result is the same, but the keepdims = True returned a 2D array with the number 6, whereas, the second incarnation returned a scalar. Similarly, when summing along axis 1 (across rows), a 2D array is returned again when keepdims = True. The last example, along axis 0 (down columns), shows a similar characteristic... dimensions are kept when keepdims = True.
Studying axes and their properties is critical to a full understanding of the power of NumPy when dealing with multidimensional data.

In [25]:
a = np.array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [1, 0, 0],
       [1, 1, 0]])
print np.sum(a, keepdims=True)


[[6]]
6
